-- 创建业务用户
CREATE USER IF NOT EXISTS 'telecom_bill'@'%' IDENTIFIED BY 'Bill@Telecom2023';
GRANT ALL PRIVILEGES ON telecom_bill.* TO 'telecom_bill'@'%';
FLUSH PRIVILEGES;

USE telecom_bill;

-- 创建计费业务表
CREATE TABLE IF NOT EXISTS test (
  ID NUMBER(10) PRIMARY KEY COMMENT '主键ID',
  MONTH CHAR(2) COMMENT '统计月份',
  USER_ID VARCHAR2(15) COMMENT '用户ID',
  SERVICE_ID VARCHAR2(30) COMMENT '用户手机号',
  COUNTER_NUMBER VARCHAR2(30) COMMENT '计费号码',
  COUNT_NUM NUMBER COMMENT '计费次数',
  CITY_CODE VARCHAR2(4) COMMENT '归属地编码',
  ADD1 NUMBER COMMENT '扩展字段1',
  ADD2 NUMBER COMMENT '扩展字段2',
  ADD3 NUMBER COMMENT '扩展字段3',
  ADD4 NUMBER COMMENT '扩展字段4',
  ADD5 NUMBER COMMENT '扩展字段5'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电信计费业务表';

-- 创建索引
CREATE INDEX idx_user_id ON test(USER_ID);
CREATE INDEX idx_service_id ON test(SERVICE_ID);
CREATE INDEX idx_month ON test(MONTH);
