-- 创建分析专用数据库
CREATE DATABASE IF NOT EXISTS ODS_TELECOM;
USE ODS_TELECOM;

-- 创建HBase映射外部表
CREATE EXTERNAL TABLE IF NOT EXISTS DWD_USER_BILL(
  ROWKEY STRING COMMENT 'HBase行键，对应源端的主键ID',
  ID STRING COMMENT '用户记录ID',
  MONTH STRING COMMENT '统计月份',
  USER_ID STRING COMMENT '用户唯一ID',
  SERVICE_ID STRING COMMENT '用户手机号',
  COUNTER_NUMBER STRING COMMENT '计费号码',
  COUNT_NUM STRING COMMENT '计费次数',
  CITY_CODE STRING COMMENT '用户归属地编码',
  ADD1 STRING COMMENT '扩展字段1',
  ADD2 STRING COMMENT '扩展字段2',
  ADD3 STRING COMMENT '扩展字段3',
  ADD4 STRING COMMENT '扩展字段4',
  ADD5 STRING COMMENT '扩展字段5'
)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES (
  "hbase.columns.mapping" = ":key,CF:ID,CF:MONTH,CF:USER_ID,CF:SERVICE_ID,CF:COUNTER_NUMBER,CF:COUNT_NUM,CF:CITY_CODE,CF:ADD1,CF:ADD2,CF:ADD3,CF:ADD4,CF:ADD5"
)
TBLPROPERTIES ("hbase.table.name" = "FK:S0");

-- 创建按天分区的用户统计结果表
CREATE TABLE IF NOT EXISTS user_daily_stat (
  user_id STRING COMMENT '用户ID',
  service_id STRING COMMENT '手机号',
  city_code STRING COMMENT '归属地',
  total_count BIGINT COMMENT '总计费次数',
  month STRING COMMENT '统计月份'
)
PARTITIONED BY (dt STRING COMMENT '统计日期')
STORED AS ORC
TBLPROPERTIES ("orc.compress"="SNAPPY");
